### PR TITLE
[PLUGIN UPDATE] Auto ZMI Faster Banking & NPC Contact

### PR DESCRIPTION
**Pull request by Jrod7938**
- Faster NPC Contact
- Faster Banking at ZMI Altar Bank

### CODE REVIEW

**Comment by R-S-55** [comment]
You are not having any issues with Rs2Npc.interact?

**Comment by Jrod7938** [comment]
Rs2Npc.interact works

**Comment by Jrod7938** [comment]
> You are not having any issues with Rs2Npc.interact?

no. It works fine for me

**Comment by R-S-55** [comment]
> > You are not having any issues with Rs2Npc.interact?
> 
> no. It works fine for me

The Rs2Npc.interact function does the following
`Microbot.getMouse().clickFast(Random.random(0, Microbot.getClient().getCanvasWidth()), Random.random(0, Microbot.getClient().getCanvasHeight()));`

How does having the mouse click a random x and y coordinate between 0 and the entire canvas width/height successfully click an npc for you? The function does nothing with the action and seemly just clicks randomly
image

**Comment by Jrod7938** [comment]
> > > You are not having any issues with Rs2Npc.interact?
> > 
> > 
> > no. It works fine for me
> 
> The Rs2Npc.interact function does the following `Microbot.getMouse().clickFast(Random.random(0, Microbot.getClient().getCanvasWidth()), Random.random(0, Microbot.getClient().getCanvasHeight()));`
> 
> How does having the mouse click a random x and y coordinate between 0 and the entire canvas width/height successfully click an npc for you? The function does nothing with the action and seemly just clicks randomly image

Scroll a little down until you see the handleMenuSwapper() function. This function is watch changes your runelite interaction to the interaction you set, then the random click is what executes the action.

**Comment by R-S-55** [comment]
> > > > You are not having any issues with Rs2Npc.interact?
> > > 
> > > 
> > > no. It works fine for me
> > 
> > 
> > The Rs2Npc.interact function does the following `Microbot.getMouse().clickFast(Random.random(0, Microbot.getClient().getCanvasWidth()), Random.random(0, Microbot.getClient().getCanvasHeight()));`
> > How does having the mouse click a random x and y coordinate between 0 and the entire canvas width/height successfully click an npc for you? The function does nothing with the action and seemly just clicks randomly image
> 
> Scroll a little down until you see the handleMenuSwapper() function. This function is watch changes your runelite interaction to the interaction you set, then the random click is what executes the action.

Do you have a discord or anywhere to chat further about development? I have a working jad plugin (prayer flicking atm) but having issues with interact function. Even when just using the dev shell and firing 
`import net.runelite.client.plugins.microbot.util.npc.Rs2Npc;
Rs2Npc.interact("doomsayer", "Toggle-warnings");`

I'd be happy to share with you when complete if you can help me understand what is going on here. Not sure if we should put in public or I imagine runelite will hide the info I am using.

**Comment by Jrod7938** [comment]
> > > > > You are not having any issues with Rs2Npc.interact?
> > > > 
> > > > 
> > > > no. It works fine for me
> > > 
> > > 
> > > The Rs2Npc.interact function does the following `Microbot.getMouse().clickFast(Random.random(0, Microbot.getClient().getCanvasWidth()), Random.random(0, Microbot.getClient().getCanvasHeight()));`
> > > How does having the mouse click a random x and y coordinate between 0 and the entire canvas width/height successfully click an npc for you? The function does nothing with the action and seemly just clicks randomly image
> > 
> > 
> > Scroll a little down until you see the handleMenuSwapper() function. This function is watch changes your runelite interaction to the interaction you set, then the random click is what executes the action.
> 
> Do you have a discord or anywhere to chat further about development? I have a working jad plugin (prayer flicking atm) but having issues with interact function. Even when just using the dev shell and firing `import net.runelite.client.plugins.microbot.util.npc.Rs2Npc; Rs2Npc.interact("doomsayer", "Toggle-warnings");`
> 
> I'd be happy to share with you when complete if you can help me understand what is going on here. Not sure if we should put in public or I imagine runelite will hide the info I am using.

We have a discord server where members will be happy to assist you further: https://discord.gg/Jtv97GrVdB

**Pull request merged**
