### PR TITLE
Tutorial Island Script

### PR DESCRIPTION
**Pull request by gmason0**
Good Afternoon, after multiple requests - I have updated the tutorial island script..

Fixes Survival Guide, Combat Tutor, Quest Guide, Mage Guide, Character Randomization & Name Generation..

I have also made a few adjustments to the Rs2Setting Classes to help work better with this & close Issue #77 as this adds config options to set the in-game settings for 'toggle music', 'toggle roofs', 'toggle disable level-up' & 'toggle shift dropping'.

One other small adjustment, for the proxy message change I have shortened this to only show the IP & Port to avoid showing the password in the titlebar...

### CODE REVIEW

**Comment by gmason0** [comment]
I just added a few recommendations from others in the discord..

**Comment by g-mason0** [comment]
No more :)

**Comment by gmason0** [comment]
Alright, I have used my last account - I purchased 20 of these to get this far... At this point, I'll see how others do & maybe improve from there...

**Review by chsami — APPROVED** [review]

**Comment by chsami** [comment]
Thanks for the contribution, this was one of the first scripts, good to see it improved :D

**Pull request merged**
