### PR TITLE
Preparing the docs

### PR DESCRIPTION
**Pull request by h0lybyte**
Updated the docs to be a bit cleaner, its under a starter astro template.

Majority of the changes are all inside of a new folder called `/astro/`. 
Currently the CNAME is pointed to my fork but should be changed to something like `docs.themicrobot.com`, which needs a CNAME to `chsami.github.io`.

TODOs are still floating around in the docs and there are some leftover boilerplate code but wasnt too sure if you want it removed or if you want to utilize it in the future? 

Examples of left over boilerplate include the generic auth system & contact form.

### CODE REVIEW

**Comment by chsami** [comment]
Really nice! Thanks a lot for this big contribution! 

Can I ask you to create the PR to development branch? 

Also how big is the astro folder atm? I'm not sure if we should add it to the microbot main repo or we should create a seperate microbot-docs repo.

Let me know what you think.

**Review by chsami — CHANGES_REQUESTED** [review]
Really nice! Thanks a lot for this big contribution!

Can I ask you to create the PR to development branch?

Also how big is the astro folder atm? I'm not sure if we should add it to the microbot main repo or we should create a seperate microbot-docs repo.

Let me know what you think.

**Comment by h0lybyte** [comment]
It would make more sense to have it be its own repo, keeping it from bloating up the workflows, since it it triggers on the main branch. 

So maybe we close this out and make a new repo called `docs.themicrobot.com` and I will just move the files over to that as a new pull request?

**Comment by h0lybyte** [comment]
https://github.com/chsami/Microbot-docs/pull/1

^ The new pull request, I will close this out.

**Pull request closed without merging**
